name: Docker Build
on:
  pull_request:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ['linux/amd64', 'linux/arm64']
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      # - name: Run QEMU manual setup
      #   run: |
      #       sudo apt update && apt upgrade -y
      #       sudo apt install make -y
      #       sudo apt install ninja-build -y
      #       sudo apt-get install libpixman-1-dev

      #       wget https://download.qemu.org/qemu-7.0.0.tar.xz
      #       tar xvJf qemu-7.0.0.tar.xz
      #       cd qemu-7.0.0
      #       ./configure
      #       make

      #       docker run --privileged --rm tonistiigi/binfmt --install all
      #       docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      - name: See if segfault is removed
        run: |
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: 'v0.9.1'
      - uses: actions/checkout@v4

      - name: Docker Build ${{ matrix.platform }}
        run: |
            docker buildx version
            tag=osb/osb-`echo ${{ matrix.platform }} | tr '/' '-'`
            set -x
            docker buildx build --platform ${{ matrix.platform }} --build-arg VERSION=`cat version.txt` --build-arg BUILD_DATE=`date -u +%Y-%m-%dT%H:%M:%SZ` -f docker/Dockerfile -t "$tag" -o type=docker .
            set +x
            docker images | grep "$tag"
